import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import VerticalNavbar from "@/components/navbar/vertical-navbar";
import ToastProvider from "@/context/toast-context";
import NotificationsListener from "@/components/notifications-listener";
import { ChatsProvider } from "@/context/chats-context";
import ClientConnectionIndicator from "@/components/client-connection-indicator";
import MobileNavbar from "@/components/navbar/mobile-navbar";
import { cookies } from "next/headers";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // Get selected theme before page loads
    const ck = await cookies();
    const theme = ck.get("current-theme");

    return (
        <html lang="en" data-theme={theme?.value || "sunset"}>
            <body
                className={`flex flex-col lg:flex-row ${geistSans.variable} ${geistMono.variable}  antialiased`}
            >
                <ClerkProvider>
                    <ToastProvider>
                        <VerticalNavbar />
                        <MobileNavbar />
                        <NotificationsListener />
                        <ChatsProvider>
                            <ClientConnectionIndicator />
                            {children}
                        </ChatsProvider>
                    </ToastProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
