import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import VerticalNavbar from "@/components/vertical-navbar";
import ToastProvider from "@/utils/context/toast-context";
import NotificationsListener from "@/components/notifications-listener";
import { ChatsProvider } from "@/utils/context/chats-context";
import ClientConnectionIndicator from "@/components/client-connection-indicator";
import ThemeLoader from "@/components/theme-loader";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" data-theme="sunset">
            <body
                className={`flex ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ClerkProvider>
                    <ThemeLoader />
                    <ToastProvider>
                        <VerticalNavbar />
                        <NotificationsListener />
                        <ChatsProvider>
                            <ClientConnectionIndicator />
                            {children}
                        </ChatsProvider>
                    </ToastProvider>
                </ClerkProvider>
            </body>
        </html>
    );
}
